# Generated by Django 5.0.6 on 2024-07-16 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_storeupload_uploaded_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictUpload",
            fields=[
                ("u_num", models.BigAutoField(primary_key=True, serialize=False)),
                ("f_name", models.CharField(max_length=255)),
                ("uploaded_file", models.FileField(null=True, upload_to="predict/")),
                (
                    "m_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "s_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.store"
                    ),
                ),
            ],
        ),
    ]
