# Generated by Django 5.0.6 on 2024-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("p_num", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField(max_length=11)),
                ("sub_category", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(max_length=11)),
                ("position", models.CharField(max_length=255)),
                ("sales", models.IntegerField(max_length=11)),
            ],
        ),
    ]
