# Generated by Django 5.0.6 on 2024-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="sales",
            field=models.IntegerField(),
        ),
    ]
