# Generated by Django 5.0.6 on 2024-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_price_alter_product_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="position",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sales",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
