# Generated by Django 5.0.6 on 2024-07-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_document"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("s_num", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("date", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("s_num", models.BigAutoField(primary_key=True, serialize=False)),
                ("s_rate", models.IntegerField()),
                ("s_date", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.AddField(
            model_name="product",
            name="date",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="s_num",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="store.store",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="p_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_records",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="s_num2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_orders",
                to="store.store",
            ),
        ),
        migrations.AddField(
            model_name="sales",
            name="p_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_records",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="sales",
            name="s_num2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_sales",
                to="store.store",
            ),
        ),
    ]
