# Generated by Django 5.0.6 on 2024-07-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_order_sales_delete_document_product_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="position",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sub_category",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="s_date",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="s_rate",
        ),
        migrations.AddField(
            model_name="product",
            name="holiday",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="date",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="holiday",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="sales",
            field=models.IntegerField(null=True),
        ),
    ]
