# Generated by Django 5.0.6 on 2024-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_remove_product_name_remove_product_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sales",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="sales",
            name="sales",
            field=models.FloatField(null=True),
        ),
    ]
