# Generated by Django 5.0.6 on 2024-07-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_product_sales_alter_sales_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="promotion",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="promotion",
            field=models.IntegerField(null=True),
        ),
    ]
