# Generated by Django 5.0.6 on 2024-07-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_product_promotion_sales_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="stock",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sales",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sales",
            name="sales",
            field=models.IntegerField(null=True),
        ),
    ]
