# Generated by Django 4.2 on 2024-07-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="c_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="m_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="qna",
            name="c_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="qna",
            name="m_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
