# Generated by Django 5.0.6 on 2024-07-11 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qna",
            name="viewcnt",
        ),
    ]
