# Generated by Django 5.0.6 on 2024-07-18 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fire_detection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="processed_file",
        ),
        migrations.AddField(
            model_name="video",
            name="processed_video",
            field=models.FileField(blank=True, null=True, upload_to="processed/"),
        ),
        migrations.AddField(
            model_name="video",
            name="store_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="video",
            name="upload_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(upload_to="originals/"),
        ),
    ]
