# Generated by Django 5.0.6 on 2024-07-20 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fire_detection",
            "0004_remove_video_video_file_video_original_video_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="original_video",
        ),
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="originals/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="processed_video",
            field=models.FileField(blank=True, null=True, upload_to="processed/"),
        ),
    ]
