# Generated by Django 5.0.6 on 2024-07-16 01:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="file",
            new_name="video_file",
        ),
    ]
